// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MemoryGameKidsBack.Models;

[Table("tblChildProfile")]
[Index("UserId", Name = "UQ__tblChild__1788CC4D0AACBDE6", IsUnique = true)]
public partial class ChildProfile
{
    [Key]
    public int ChildId { get; set; }

    public int? UserId { get; set; }

    [StringLength(100)]
    public string ParentName { get; set; }

    [StringLength(20)]
    public string ParentNumber { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public int? DoctorId { get; set; }

    public int? ClinicId { get; set; }

    public bool? IsDeleted { get; set; }

    [ForeignKey("ClinicId")]
    [InverseProperty("tblChildProfiles")]
    public virtual ClinicProfile Clinic { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("tblChildProfiles")]
    public virtual DoctorProfile Doctor { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("tblChildProfile")]
    public virtual User User { get; set; }
}