// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MemoryGameKidsBack.Models;

[Table("tblClinicProfile")]
[Index("UserId", Name = "UQ__tblClini__1788CC4D101FAD3B", IsUnique = true)]
public partial class ClinicProfile
{
    [Key]
    public int ClinicId { get; set; }

    public int? UserId { get; set; }

    [StringLength(100)]
    public string ClinicName { get; set; }

    [StringLength(200)]
    public string Address { get; set; }

    [StringLength(20)]
    public string Phone { get; set; }

    public bool? IsDeleted { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("tblClinicProfile")]
    public virtual User User { get; set; }

    [InverseProperty("Clinic")]
    public virtual ICollection<ChildProfile> tblChildProfiles { get; set; } = new List<ChildProfile>();

    [InverseProperty("Clinic")]
    public virtual ICollection<DoctorProfile> tblDoctorProfiles { get; set; } = new List<DoctorProfile>();
}