// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MemoryGameKidsBack.Models;

[Table("lkpGame")]
public partial class Game
{
    [Key]
    public int GameId { get; set; }

    public int? CategoryId { get; set; }

    [StringLength(100)]
    public string GameName { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    public bool? IsDeleted { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("lkpGames")]
    public virtual GameCategory Category { get; set; }

    [InverseProperty("Game")]
    public virtual ICollection<GameSession> tblGameSessions { get; set; } = new List<GameSession>();
}