// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MemoryGameKidsBack.Models;

[Table("tblGameSession")]
public partial class GameSession
{
    [Key]
    public int SessionId { get; set; }

    public int? UserId { get; set; }

    public int? GameId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? StartTime { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? EndTime { get; set; }

    public int? Score { get; set; }

    public int? Trials { get; set; }

    public int? Misses { get; set; }

    public DateOnly? SessionDate { get; set; }

    [ForeignKey("GameId")]
    [InverseProperty("tblGameSessions")]
    public virtual Game Game { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("tblGameSessions")]
    public virtual User User { get; set; }
}