// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MemoryGameKidsBack.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MemoryGameKidsBack.Models
{
    public partial interface IKidsMemoreyTestDBContextProcedures
    {
        Task<int> sp_AddGameSessionAsync(int? userId, int? gameId, int? score, int? trials, int? misses, DateTime? endTime, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetDoctorDashboardResult>> sp_GetDoctorDashboardAsync(int? doctorId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_RegisterUserAsync(int? userTypeId, string email, string password, string name, string extraInfo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
