// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MemoryGameKidsBack.Models;

[Table("tblMemoryScoreSummary")]
public partial class MemoryScoreSummary
{
    [Key]
    public int SummaryId { get; set; }

    public int? UserId { get; set; }

    public double? ShortTermScore { get; set; }

    public double? LongTermScore { get; set; }

    public double? AuditoryScore { get; set; }

    public double? VisualScore { get; set; }

    public double? TotalScore { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("tblMemoryScoreSummaries")]
    public virtual User User { get; set; }
}