// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MemoryGameKidsBack.Models;

[Table("tblUser")]
[Index("Email", Name = "UQ__tblUser__A9D105341C4D9A8E", IsUnique = true)]
public partial class User
{
    [Key]
    public int UserId { get; set; }

    public int? UserTypeId { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [StringLength(200)]
    public string UserPassword { get; set; }

    public bool? IsDeleted { get; set; }

    [ForeignKey("UserTypeId")]
    [InverseProperty("tblUsers")]
    public virtual UserType UserType { get; set; }

    [InverseProperty("User")]
    public virtual ChildProfile tblChildProfile { get; set; }

    [InverseProperty("User")]
    public virtual ClinicProfile tblClinicProfile { get; set; }

    [InverseProperty("User")]
    public virtual DoctorProfile tblDoctorProfile { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<GameSession> tblGameSessions { get; set; } = new List<GameSession>();

    [InverseProperty("User")]
    public virtual ICollection<MemoryScoreSummary> tblMemoryScoreSummaries { get; set; } = new List<MemoryScoreSummary>();
}