// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MemoryGameKidsBack.Models;

[Table("lkpUserType")]
public partial class UserType
{
    [Key]
    public int UserTypeId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(200)]
    public string Description { get; set; }

    public bool? IsDeleted { get; set; }

    [InverseProperty("UserType")]
    public virtual ICollection<User> tblUsers { get; set; } = new List<User>();
}