// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MemoryGameKidsBack.Models;

[Table("tblDoctorProfile")]
[Index("UserId", Name = "UQ__tblDocto__1788CC4DB7894790", IsUnique = true)]
public partial class DoctorProfile
{
    [Key]
    public int DoctorId { get; set; }

    public int? UserId { get; set; }

    public int? ClinicId { get; set; }

    [StringLength(100)]
    public string FullName { get; set; }

    [StringLength(100)]
    public string Specialty { get; set; }

    [StringLength(50)]
    public string LicenseNumber { get; set; }

    public bool? IsDeleted { get; set; }

    [ForeignKey("ClinicId")]
    [InverseProperty("tblDoctorProfiles")]
    public virtual ClinicProfile Clinic { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("tblDoctorProfile")]
    public virtual User User { get; set; }

    [InverseProperty("Doctor")]
    public virtual ICollection<ChildProfile> tblChildProfiles { get; set; } = new List<ChildProfile>();
}