// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MemoryGameKidsBack.Models;

public partial class KidsMemoreyTestDBContext : DbContext
{
    public KidsMemoreyTestDBContext()
    {
    }

    public KidsMemoreyTestDBContext(DbContextOptions<KidsMemoreyTestDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Game> lkpGames { get; set; }

    public virtual DbSet<GameCategory> lkpGameCategories { get; set; }

    public virtual DbSet<UserType> lkpUserTypes { get; set; }

    public virtual DbSet<ChildProfile> tblChildProfiles { get; set; }

    public virtual DbSet<ClinicProfile> tblClinicProfiles { get; set; }

    public virtual DbSet<DoctorProfile> tblDoctorProfiles { get; set; }

    public virtual DbSet<GameSession> tblGameSessions { get; set; }

    public virtual DbSet<MemoryScoreSummary> tblMemoryScoreSummaries { get; set; }

    public virtual DbSet<User> tblUsers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Game>(entity =>
        {
            entity.HasKey(e => e.GameId).HasName("PK__lkpGame__2AB897FDE15DA297");

            entity.Property(e => e.IsDeleted).HasDefaultValue(false);

            entity.HasOne(d => d.Category).WithMany(p => p.lkpGames).HasConstraintName("FK__lkpGame__Categor__6477ECF3");
        });

        modelBuilder.Entity<GameCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__lkpGameC__19093A0B809F5511");
        });

        modelBuilder.Entity<UserType>(entity =>
        {
            entity.HasKey(e => e.UserTypeId).HasName("PK__lkpUserT__40D2D816FAB82BF9");

            entity.Property(e => e.IsDeleted).HasDefaultValue(false);
        });

        modelBuilder.Entity<ChildProfile>(entity =>
        {
            entity.HasKey(e => e.ChildId).HasName("PK__tblChild__BEFA07160C19D1A2");

            entity.Property(e => e.IsDeleted).HasDefaultValue(false);

            entity.HasOne(d => d.Clinic).WithMany(p => p.tblChildProfiles).HasConstraintName("FK__tblChildP__Clini__5EBF139D");

            entity.HasOne(d => d.Doctor).WithMany(p => p.tblChildProfiles).HasConstraintName("FK__tblChildP__Docto__5DCAEF64");

            entity.HasOne(d => d.User).WithOne(p => p.tblChildProfile).HasConstraintName("FK__tblChildP__UserI__5CD6CB2B");
        });

        modelBuilder.Entity<ClinicProfile>(entity =>
        {
            entity.HasKey(e => e.ClinicId).HasName("PK__tblClini__3347C2DD88971289");

            entity.Property(e => e.IsDeleted).HasDefaultValue(false);

            entity.HasOne(d => d.User).WithOne(p => p.tblClinicProfile).HasConstraintName("FK__tblClinic__UserI__52593CB8");
        });

        modelBuilder.Entity<DoctorProfile>(entity =>
        {
            entity.HasKey(e => e.DoctorId).HasName("PK__tblDocto__2DC00EBFC720000D");

            entity.Property(e => e.IsDeleted).HasDefaultValue(false);

            entity.HasOne(d => d.Clinic).WithMany(p => p.tblDoctorProfiles).HasConstraintName("FK__tblDoctor__Clini__5812160E");

            entity.HasOne(d => d.User).WithOne(p => p.tblDoctorProfile).HasConstraintName("FK__tblDoctor__UserI__571DF1D5");
        });

        modelBuilder.Entity<GameSession>(entity =>
        {
            entity.HasKey(e => e.SessionId).HasName("PK__tblGameS__C9F492900AD0EB61");

            entity.ToTable("tblGameSession", tb => tb.HasTrigger("trg_UpdateMemorySummary"));

            entity.Property(e => e.EndTime).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.SessionDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.StartTime).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Game).WithMany(p => p.tblGameSessions).HasConstraintName("FK__tblGameSe__GameI__693CA210");

            entity.HasOne(d => d.User).WithMany(p => p.tblGameSessions).HasConstraintName("FK__tblGameSe__UserI__68487DD7");
        });

        modelBuilder.Entity<MemoryScoreSummary>(entity =>
        {
            entity.HasKey(e => e.SummaryId).HasName("PK__tblMemor__DAB10E2FB5D318C4");

            entity.Property(e => e.AuditoryScore).HasDefaultValue(0.0);
            entity.Property(e => e.LongTermScore).HasDefaultValue(0.0);
            entity.Property(e => e.ShortTermScore).HasDefaultValue(0.0);
            entity.Property(e => e.TotalScore).HasDefaultValue(0.0);
            entity.Property(e => e.VisualScore).HasDefaultValue(0.0);

            entity.HasOne(d => d.User).WithMany(p => p.tblMemoryScoreSummaries).HasConstraintName("FK__tblMemory__UserI__6EF57B66");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__tblUser__1788CC4CDC6A33DA");

            entity.ToTable("tblUser", tb => tb.HasTrigger("trg_CreateScoreSummaryOnNewUser"));

            entity.Property(e => e.IsDeleted).HasDefaultValue(false);

            entity.HasOne(d => d.UserType).WithMany(p => p.tblUsers).HasConstraintName("FK__tblUser__UserTyp__4D94879B");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}