// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MemoryGameKidsBack.Models
{
    public partial class sp_GetDoctorDashboardResult
    {
        public int ChildId { get; set; }
        [StringLength(100)]
        public string ParentName { get; set; }
        [StringLength(100)]
        public string GameName { get; set; }
        public int? Score { get; set; }
        public DateOnly? SessionDate { get; set; }
    }
}
